version: "3.9"
services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase-prod
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
      - metabase-data:/metabase-data # Persist Metabase application data
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: mysecretpassword
      MB_DB_HOST: postgres
    networks:
      - metanet1
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:16-alpine
    container_name: postgres-prod
    hostname: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: metabase
      POSTGRES_DB: metabaseappdb
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persist PostgreSQL data
    networks:
      - metanet1

networks:
  metanet1:
    driver: bridge

volumes:
  metabase-data:
    driver: local # Persist Metabase application data
  postgres-data:
    driver: local # Persist PostgreSQL data
